#!/usr/bin/php
<?php
define('APP', '/srv/http/app/');
include('/srv/http/app/libs/runeaudio.php');

$redis = new Redis();
$redis->connect( '/tmp/redis.sock' );

switch( $argv[ 1 ] ) {
    case "on":
        wrk_startAirplay( $redis );
		exec( '/usr/bin/systemctl stop mpd' );
		ui_render( 'playback', '{"activePlayer":"Airplay"}' );
        ui_notify( 'AirPlay Start', 'Playback switched to Airplay.' );
        break;
    case "off":
        wrk_stopAirplay($redis);
		exec( '/usr/bin/systemctl start mpd' );
		ui_render( 'playback', '{"activePlayer":"MPD"}' );
        ui_notify( 'AirPlay Stop', 'Playback switched to MPD.' );
        break;
}
ui_libraryHome($redis);
