#!/usr/bin/php
<?php 
include( '/srv/http/app/libs/runeaudio.php' );

while ( 1 ) {
	$redis = new Redis();
	$redis->pconnect( '/tmp/redis.sock' );
	$socket = openMpdSocket( '/run/mpd.sock' );
	if ( !$socket ) {
		sleep( 3 );
	} else {
		do {
			$status = monitorMpdState( $socket );
			$changed = $status[ 'changed' ];
			ui_render( 'idle', json_encode( $changed ) );
			$status = ui_status( $socket, $status );
			if ( $changed === 'mixer'
				&& $redis->get( 'ao' ) === 'PianoDACPlus'
				&& $redis->hget( 'mpdconf', 'mixer_type' ) === 'hardware'
			) {
				$volume = exec( 'mpc volume | cut -d' ' -f2' );
				sysCmd( 'amixer -D '.json_decode( $redis->hget( 'acards', 'PianoDACPlus' ) )->mixer_device.' set Subwoofer '.$volume );
			}
			$errorcode = socket_last_error( $socket );
		} while ( !$errorcode );
		$redis->close();
		closeMpdSocket( $socket );
		$redis->close();
	}
}
